version: '3'
services:
    # SQL Server を立ち上げる
    db:
        image: mcr.microsoft.com/mssql/server:2019-CU6-ubuntu-16.04
        container_name: schemaspy-sqlserver
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password@12345
            - MSSQL_PID=Express
        networks: 
            - schemaspy_net
    
    # SQL Server の立ち上がりを待機する
    wait_db:
        image: mcr.microsoft.com/mssql-tools
        container_name: mssql-tools
        environment: 
            - SQLSERVER_HOST=${SQLSERVER_HOST}
            - SQLSERVER_USER=${SQLSERVER_USER}
            - SQLSERVER_PASS=${SQLSERVER_PASS}
        command: bash wait_db.sh
        volumes: 
            - ./wait_db.sh:/wait_db.sh
        networks: 
            - schemaspy_net
    
    # SQL を実行し DB を初期化する
    create_db:
        image: mcr.microsoft.com/mssql-tools
        container_name: mssql-tools
        command: /opt/mssql-tools/bin/sqlcmd -S schemaspy-sqlserver -U sa -P Password@12345 -i /sql/create_db.sql
        volumes: 
            - ./sql:/sql
        networks: 
            - schemaspy_net
    create_table:
        image: mcr.microsoft.com/mssql-tools
        container_name: mssql-tools
        command: /opt/mssql-tools/bin/sqlcmd -S schemaspy-sqlserver -U sa -P Password@12345 -i /sql/create_table.sql
        volumes: 
            - ./sql:/sql
        networks: 
            - schemaspy_net
    add_comment:
        image: mcr.microsoft.com/mssql-tools
        container_name: mssql-tools
        command: /opt/mssql-tools/bin/sqlcmd -S schemaspy-sqlserver -U sa -P Password@12345 -i /sql/add_comment.sql
        volumes: 
            - ./sql:/sql
        networks: 
            - schemaspy_net

    # ドキュメントを作成する
    schemaspy:
        image: schemaspy/schemaspy:snapshot
        container_name: schemaspy
        volumes: 
            - ./output:/output
            - ./schemaspy.properties:/schemaspy.properties
            - ./mssql-jdbc-8.4.1.jre8.jar:/drivers/mssql-jdbc-8.4.1.jre8.jar
        networks: 
            - schemaspy_net
        command: -vizjs
networks:
    schemaspy_net:
        external: false