version: '3'
services:
    # SQL Server を立ち上げる
    db:
        build: .
        image: mysql-schemaspy
        container_name: ${SERVER_HOST}
        environment: 
            - MYSQL_DATABASE=${SERVER_DB}
            - MYSQL_ROOT_PASSWORD=${SERVER_PASS}
        networks: 
            - schemaspy_net

    # SQL Server の立ち上がりを待機する
    wait_db:
        image: mysql:8.0.21
        container_name: wait_db
        environment: 
            - SERVER_HOST=${SERVER_HOST}
            - SERVER_DB=${SERVER_DB}
            - SERVER_USER=${SERVER_USER}
            - SERVER_PASS=${SERVER_PASS}
        command: bash wait_db.sh
        volumes: 
            - ./wait_db.sh:/wait_db.sh
        networks: 
            - schemaspy_net
    
    # SQL を実行し DB を初期化する
    create_table:
        build: .
        image: mysql-schemaspy
        container_name: create_table
        command: bash -c "/usr/bin/mysql --host=${SERVER_HOST} --database=${SERVER_DB} --user=${SERVER_USER} --password=${SERVER_PASS} < /sql/create_table.sql"
        volumes: 
            - ./sql:/sql
        networks: 
            - schemaspy_net

    # ドキュメントを作成する
    schemaspy:
        image: schemaspy/schemaspy:snapshot
        container_name: schemaspy
        volumes: 
            - ./output:/output
            - ./schemaspy.properties:/schemaspy.properties
            - ./mysql-connector-java-8.0.21.jar:/drivers/mysql-connector-java-8.0.21.jar
        networks: 
            - schemaspy_net
        command: -vizjs -host ${SERVER_HOST} -u ${SERVER_USER} -p ${SERVER_PASS}
networks:
    schemaspy_net:
        external: false